version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "daily"
    groups:
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"
